// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { EmptyArgs, MessageOptions } from 'loclizr'

export type ErrorsKey = 'forbidden' | 'not_found' | 'rate_limited'
export interface ErrorsArgs {
  forbidden: EmptyArgs
  not_found: EmptyArgs
  rate_limited: { seconds: number }
}
export declare const errors: Readonly<{
  [K in ErrorsKey]: (args: ErrorsArgs[K], opts?: MessageOptions) => string
}>

export type TermsKey = 'accept' | 'bare' | 'dropped' | 'notice' | 'title'
export interface TermsArgs<T> {
  accept: { link: (chunks: readonly (string | T)[]) => T }
  bare: { link: (chunks: readonly (string | T)[]) => T }
  dropped: { notice: (chunks: readonly (string | T)[]) => T }
  notice: { count: number; b: (chunks: readonly (string | T)[]) => T }
  title: EmptyArgs
}
export interface TermsReturn<T> {
  accept: readonly (string | T)[]
  bare: string
  dropped: readonly (string | T)[]
  notice: readonly (string | T)[]
  title: string
}
export declare const terms: Readonly<{
  [K in TermsKey]: <T>(args: TermsArgs<T>[K], opts?: MessageOptions) => TermsReturn<T>[K]
}>
