// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
import { errors_forbidden, errors_not_found, errors_rate_limited } from './messages/errors.js'
import { terms_accept, terms_bare, terms_dropped, terms_notice, terms_title } from './messages/terms.js'

export const errors = /*#__PURE__*/ Object.freeze({
  __proto__: null,
  forbidden: errors_forbidden,
  not_found: errors_not_found,
  rate_limited: errors_rate_limited,
})

export const terms = /*#__PURE__*/ Object.freeze({
  __proto__: null,
  accept: terms_accept,
  bare: terms_bare,
  dropped: terms_dropped,
  notice: terms_notice,
  title: terms_title,
})
