// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
export { getLocale, setLocale, subscribe } from 'loclizr'
export { locales, sourceLocale } from './messages/_locale.js'
export * from './messages/cart.js'
export * from './messages/dev.js'
export * from './messages/errors.js'
export * from './messages/nav.js'
export * from './messages/order.js'
export * from './messages/terms.js'
