// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { SetLocaleOptions } from 'loclizr'

export type AppLocale = 'de' | 'de-AT' | 'en'

declare module 'loclizr' {
  interface LocaleRegistry {
    locale: AppLocale
  }
}

export declare function getLocale(): AppLocale
export declare function setLocale(locale: AppLocale, options?: SetLocaleOptions): void
export declare function subscribe(listener: () => void): () => void
export { locales, sourceLocale } from './messages/_locale.js'
export * from './messages/cart.js'
export * from './messages/dev.js'
export * from './messages/errors.js'
export * from './messages/nav.js'
export * from './messages/order.js'
export * from './messages/terms.js'
