import { mkdir, mkdtemp, readFile, readdir, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import type { EmittedFile } from '../types'
import { GENERATED_HEADER, syncOutput } from './output'

const OUT_DIR = 'src/loclizr'
const RECORD = 'locales/loclizr.context.json'

let root = ''

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'loclizr-output-'))
})

afterEach(async () => {
  await rm(root, { recursive: true, force: true })
})

function generated(body: string): string {
  return `${GENERATED_HEADER}\n${body}\n`
}

function file(path: string, body: string): EmittedFile {
  return { path, contents: generated(body) }
}

async function seed(path: string, contents: string): Promise<void> {
  const absolute = join(root, path)
  await mkdir(dirname(absolute), { recursive: true })
  await writeFile(absolute, contents, 'utf8')
}

async function read(path: string): Promise<string | null> {
  try {
    return await readFile(join(root, path), 'utf8')
  } catch {
    return null
  }
}

function codes(diagnostics: readonly { readonly code: string }[]): readonly string[] {
  return diagnostics.map((diagnostic) => diagnostic.code)
}

function recordBytes(
  overrides: {
    readonly source?: string
    readonly usage?: readonly unknown[]
    readonly translations?: readonly unknown[]
  } = {},
): string {
  const body = {
    schema: 1,
    sourceLocale: 'en',
    locales: ['de', 'en'],
    messages: [
      {
        key: 'nav.home',
        id: 'nav_home',
        module: 'messages/nav.js',
        kind: 'text',
        source: overrides.source ?? 'Home',
        sourceHash: '3a78695388b38b5c',
        description: null,
        args: [],
        variants: [],
        markup: [],
        translations: overrides.translations ?? [
          { locale: 'de', status: 'translated', from: null, reason: null },
        ],
        usage: overrides.usage ?? [],
      },
    ],
  }
  return `${JSON.stringify(body, null, 2)}\n`
}

describe('the generated header', () => {
  // M6 prints this token and the prune keys on it. Two copies that drift make
  // every generated file on disk look foreign: nothing is written, nothing is
  // pruned, and the build still exits 0.
  it('is exactly the byte sequence every generated file opens with', () => {
    expect(GENERATED_HEADER).toBe(
      '// @generated by loclizr abi=1. Do not edit; run `loclizr build`.',
    )
  })
})

describe('syncOutput in build mode', () => {
  it('writes every emitted file and reports its path relative to the root', async () => {
    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}'), file('messages/nav.js', 'export function nav() {}')],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
    expect(result.written).toEqual(['src/loclizr/messages.js', 'src/loclizr/messages/nav.js'])
    expect(await read('src/loclizr/messages/nav.js')).toBe(generated('export function nav() {}'))
  })

  it('leaves a byte-identical file alone and reports it as unwritten', async () => {
    const unchanged = file('messages.js', 'export {}')
    await seed('src/loclizr/messages.js', unchanged.contents)

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [unchanged],
      record: null,
    })

    expect(result.written).toEqual([])
    expect(result.diagnostics).toEqual([])
  })

  // A lone surrogate cannot be encoded, so the file on disk holds U+FFFD where
  // the emitted string held half an emoji. Comparing the two directly would
  // rewrite the file on every build and no run would ever settle.
  it('settles on content the encoder cannot carry unchanged', async () => {
    const half = file('messages/odd.js', 'export const pair = `\uD800`')
    const first = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [half],
      record: null,
    })

    const second = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [half],
      record: null,
    })

    expect(first.written).toEqual(['src/loclizr/messages/odd.js'])
    expect(second.written).toEqual([])
    expect(second.diagnostics).toEqual([])
  })

  it('leaves no temporary file behind', async () => {
    await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(await readdir(join(root, OUT_DIR))).toEqual(['messages.js'])
  })

  it('skips a path occupied by a file carrying no generated header', async () => {
    await seed('src/loclizr/messages.js', 'export const mine = 1\n')

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ1021'])
    expect(result.diagnostics[0]?.file).toBe('src/loclizr/messages.js')
    expect(result.written).toEqual([])
    expect(await read('src/loclizr/messages.js')).toBe('export const mine = 1\n')
  })

  it('prunes a headered file this emit did not produce', async () => {
    await seed('src/loclizr/messages/old.js', generated('export function old() {}'))
    await seed('src/loclizr/messages/old.d.ts', generated('export declare function old(): string'))

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages/nav.js', 'export function nav() {}')],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
    expect(await read('src/loclizr/messages/old.js')).toBeNull()
    expect(await read('src/loclizr/messages/old.d.ts')).toBeNull()
    expect(await read('src/loclizr/messages/nav.js')).not.toBeNull()
  })

  it('keeps a foreign file byte-identical and reports it (prune-keeps-foreign)', async () => {
    await seed('src/loclizr/keep.ts', 'export const keep = 1\n')

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ1021'])
    expect(result.diagnostics[0]?.file).toBe('src/loclizr/keep.ts')
    expect(result.diagnostics[0]?.severity).toBe('warn')
    expect(result.diagnostics[0]?.fatal).toBe(false)
    expect(await read('src/loclizr/keep.ts')).toBe('export const keep = 1\n')
  })

  it('writes the .gitignore only when it is absent', async () => {
    const gitignore: EmittedFile = { path: '.gitignore', contents: '*\n!.gitignore\n' }

    const first = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [gitignore],
      record: null,
    })
    expect(first.written).toEqual(['src/loclizr/.gitignore'])

    await seed('src/loclizr/.gitignore', '# emptied by the team that commits outDir\n')
    const second = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [gitignore],
      record: null,
    })

    expect(second.written).toEqual([])
    expect(second.diagnostics).toEqual([])
    expect(await read('src/loclizr/.gitignore')).toBe(
      '# emptied by the team that commits outDir\n',
    )
  })

  it('never prunes the .gitignore and never reports it as foreign', async () => {
    await seed('src/loclizr/.gitignore', '*\n!.gitignore\n')

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
    expect(await read('src/loclizr/.gitignore')).toBe('*\n!.gitignore\n')
  })

  it('reports output-unwritable and stops at the first failure', async () => {
    await seed('src/loclizr', 'outDir is a file\n')

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}'), file('messages/nav.js', 'export {}')],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5001'])
    expect(result.diagnostics[0]?.fatal).toBe(true)
    expect(result.written).toEqual([])
    expect(await read(RECORD)).toBeNull()
  })
})

describe('syncOutput in check mode', () => {
  it('writes nothing at all', async () => {
    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}'), { path: '.gitignore', contents: '*\n' }],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(result.written).toEqual([])
    expect(await read('src/loclizr/messages.js')).toBeNull()
    expect(await read('src/loclizr/.gitignore')).toBeNull()
    expect(await read(RECORD)).toBeNull()
  })

  // `check` never fails on a file `build` tolerates, and what `build` left on
  // disk is the encodable form of what emit produced.
  it('calls a file build already settled on current', async () => {
    const half = file('messages/odd.js', 'export const pair = `\uD800`')
    await seed('src/loclizr/messages/odd.js', half.contents)

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [half],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
  })

  it('reports output-stale for an emitted file that exists and differs', async () => {
    await seed('src/loclizr/messages.js', generated('export function stale() {}'))

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5002'])
    expect(result.diagnostics[0]?.file).toBe('src/loclizr/messages.js')
  })

  // The tree ignores itself by default, so telling the reader to stop
  // committing it, or to commit the rebuilt file, is advice about a state the
  // build already prevents. The remedy is one command.
  it('drops the committing advice while outDir carries its own .gitignore', async () => {
    await seed('src/loclizr/.gitignore', '*\n!.gitignore\n')
    await seed('src/loclizr/messages.js', generated('export function stale() {}'))
    await seed('src/loclizr/messages/old.js', generated('export function old() {}'))

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5002', 'LZ5002'])
    expect(result.diagnostics[0]?.hint).toBe(
      'the generated tree on disk is stale; run `loclizr build`.',
    )
    expect(result.diagnostics[1]?.hint).toBe('run `loclizr build`, which prunes it.')
  })

  it('asks for the result to be committed once the team deleted that .gitignore', async () => {
    await seed('src/loclizr/messages.js', generated('export function stale() {}'))
    await seed('src/loclizr/messages/old.js', generated('export function old() {}'))

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(result.diagnostics[0]?.hint).toBe('run `loclizr build` and commit the result.')
    expect(result.diagnostics[1]?.hint).toBe(
      'run `loclizr build`, which prunes it, and commit the result.',
    )
  })

  it('reports nothing for an emitted file that is absent from disk', async () => {
    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
  })

  it('never compares the .gitignore, whatever it holds', async () => {
    await seed('src/loclizr/.gitignore', '# emptied by the team that commits outDir\n')

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [{ path: '.gitignore', contents: '*\n!.gitignore\n' }],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
  })

  it('reports an orphaned headered file and keeps it', async () => {
    await seed('src/loclizr/messages/old.js', generated('export function old() {}'))

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5002'])
    expect(result.diagnostics[0]?.message).toContain('orphaned')
    expect(await read('src/loclizr/messages/old.js')).not.toBeNull()
  })

  it('reports a headerless file exactly as build does, never as output-stale', async () => {
    await seed('src/loclizr/keep.ts', 'export const keep = 1\n')
    await seed('src/loclizr/messages.js', 'hand written, no header\n')

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ1021', 'LZ1021'])
  })

  it('never tells the reader a write was skipped, because check attempts none', async () => {
    await seed('src/loclizr/messages.js', 'hand written, no header\n')

    const checked = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })
    const built = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(checked.diagnostics[0]?.message).toBe(
      '`src/loclizr/messages.js` does not carry the generated header, so the generated file it occupies is not the one this build would write.',
    )
    expect(built.diagnostics[0]?.message).toBe(
      '`src/loclizr/messages.js` does not carry the generated header, so the generated file it occupies was not written.',
    )
  })
})

// LZ1007 decides containment lexically, on a path nothing resolves through the
// filesystem, and a symlink is committable to git. The prune deletes files, so
// the second bound on it has to survive one.
describe('a symlink out of the project root on the way to a generated file', () => {
  const PROJECT = 'project'
  const VICTIM = 'outside/victim.js'

  async function linkOut(): Promise<string> {
    await mkdir(join(root, PROJECT, 'src'), { recursive: true })
    await seed(VICTIM, generated('export const theirs = 1'))
    await symlink(join(root, 'outside'), join(root, PROJECT, OUT_DIR), 'dir')
    return join(root, PROJECT)
  }

  it('writes nothing, deletes nothing and reports it as unwritable', async () => {
    const project = await linkOut()

    const result = await syncOutput({
      mode: 'build',
      root: project,
      outDir: OUT_DIR,
      files: [{ path: '.gitignore', contents: '*\n!.gitignore\n' }, file('messages.js', 'export {}')],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5001'])
    expect(result.diagnostics[0]?.severity).toBe('error')
    expect(result.diagnostics[0]?.fatal).toBe(true)
    expect(result.diagnostics[0]?.file).toBe(OUT_DIR)
    expect(result.diagnostics[0]?.message).toBe(
      '`src/loclizr` resolves outside the project root, so nothing under it was written or pruned.',
    )
    expect(result.written).toEqual([])
    expect(await read(VICTIM)).toBe(generated('export const theirs = 1'))
    expect(await read('outside/.gitignore')).toBeNull()
    expect(await read('outside/messages.js')).toBeNull()
    expect(await read(`${PROJECT}/${RECORD}`)).toBeNull()
  })

  it('refuses in check too, rather than reporting files it does not own', async () => {
    const project = await linkOut()

    const result = await syncOutput({
      mode: 'check',
      root: project,
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5001'])
  })

  it('refuses a dangling link, whose target nobody has chosen yet', async () => {
    await mkdir(join(root, PROJECT, 'src'), { recursive: true })
    await symlink(join(root, 'not-created-yet'), join(root, PROJECT, OUT_DIR), 'dir')

    const result = await syncOutput({
      mode: 'build',
      root: join(root, PROJECT),
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    // Pinned to the refusal's own text: a write attempted through the link and
    // failing on its own would report the same code against a different path.
    expect(result.diagnostics[0]?.message).toBe(
      '`src/loclizr` resolves outside the project root, so nothing under it was written or pruned.',
    )
    expect(result.written).toEqual([])
    expect(await read('not-created-yet/messages.js')).toBeNull()
  })

  it('refuses a link committed one level below outDir, which the sweep also refuses', async () => {
    const project = join(root, PROJECT)
    await mkdir(join(project, OUT_DIR), { recursive: true })
    await mkdir(join(root, 'outside'), { recursive: true })
    await symlink(join(root, 'outside'), join(project, OUT_DIR, 'messages'), 'dir')

    const result = await syncOutput({
      mode: 'build',
      root: project,
      outDir: OUT_DIR,
      files: [file('messages/nav.js', 'export const nav = 1')],
      record: null,
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5001'])
    expect(result.written).toEqual([])
    expect(await read('outside/nav.js')).toBeNull()
  })

  // Containment is outDir's rule, because outDir is where files are deleted. A
  // catalogs directory shared across a monorepo through a link is an ordinary
  // shape, and the record is written beside the catalogs by design.
  it('still writes the record into a catalogs directory reached through a link', async () => {
    const project = join(root, PROJECT)
    await mkdir(project, { recursive: true })
    await mkdir(join(root, 'shared'), { recursive: true })
    await symlink(join(root, 'shared'), join(project, 'locales'), 'dir')

    const result = await syncOutput({
      mode: 'build',
      root: project,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(result.diagnostics).toEqual([])
    expect(result.written).toEqual([RECORD])
    expect(await read('shared/loclizr.context.json')).toBe(recordBytes())
  })
})

// Both sides of the containment test go through realpath, because a macOS
// tmpdir under /var is itself a link to /private/var: a real path compared
// against a lexical root would refuse every build run from there.
describe('a project root reached through a symlink of its own', () => {
  it('writes the tree as if the root had been spelled out', async () => {
    await mkdir(join(root, 'real'), { recursive: true })
    await symlink(join(root, 'real'), join(root, 'linked'), 'dir')

    const result = await syncOutput({
      mode: 'build',
      root: join(root, 'linked'),
      outDir: OUT_DIR,
      files: [file('messages.js', 'export {}')],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
    expect(result.written).toEqual(['src/loclizr/messages.js'])
    expect(await read('real/src/loclizr/messages.js')).toBe(generated('export {}'))
  })
})

describe('an outDir symlinked to another directory inside the root', () => {
  it('writes and prunes through it, because containment is the rule and not the link', async () => {
    await seed('src/generated/messages/old.js', generated('export const old = 1'))
    await symlink(join(root, 'src/generated'), join(root, OUT_DIR), 'dir')

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [file('messages/nav.js', 'export const nav = 1')],
      record: null,
    })

    expect(result.diagnostics).toEqual([])
    expect(result.written).toEqual(['src/loclizr/messages/nav.js'])
    expect(await read('src/generated/messages/nav.js')).toBe(generated('export const nav = 1'))
    expect(await read('src/generated/messages/old.js')).toBeNull()
  })
})

describe('the record gate', () => {
  it('writes the full record when any byte differs', async () => {
    await seed(RECORD, recordBytes({ usage: [] }))

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes({ usage: [{ file: 'src/Nav.tsx', scope: 'Nav' }] }) },
    })

    expect(result.written).toEqual([RECORD])
    expect(await read(RECORD)).toContain('src/Nav.tsx')
  })

  it('raises no record-rewritten when only usage and translations moved', async () => {
    await seed(RECORD, recordBytes({ usage: [] }))

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [],
      record: {
        path: RECORD,
        bytes: recordBytes({
          usage: [{ file: 'src/Nav.tsx', scope: 'Nav' }],
          translations: [{ locale: 'de', status: 'fallback', from: 'en', reason: 'missing' }],
        }),
      },
    })

    expect(result.diagnostics).toEqual([])
  })

  it('raises record-rewritten when the contract changed', async () => {
    await seed(RECORD, recordBytes({ source: 'Home' }))

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes({ source: 'Start' }) },
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5007'])
    expect(result.diagnostics[0]?.severity).toBe('warn')
    expect(result.written).toEqual([RECORD])
  })

  it('raises nothing on the first build, when no record is committed yet', async () => {
    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(result.diagnostics).toEqual([])
    expect(result.written).toEqual([RECORD])
  })

  it('writes nothing when the committed record is byte-identical', async () => {
    await seed(RECORD, recordBytes())

    const result = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(result.written).toEqual([])
    expect(result.diagnostics).toEqual([])
  })

  it('check raises record-stale when the contract changed', async () => {
    await seed(RECORD, recordBytes({ source: 'Home' }))

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes({ source: 'Start' }) },
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5003'])
    expect(result.diagnostics[0]?.severity).toBe('error')
  })

  it('check passes when only usage and translations moved', async () => {
    await seed(RECORD, recordBytes({ usage: [{ file: 'src/Old.tsx', scope: 'Old' }] }))

    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes({ usage: [{ file: 'src/New.tsx', scope: 'New' }] }) },
    })

    expect(result.diagnostics).toEqual([])
  })

  it('check raises record-stale when the record was never committed', async () => {
    const result = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes() },
    })

    expect(codes(result.diagnostics)).toEqual(['LZ5003'])
  })

  it('treats an unparseable committed record as differing', async () => {
    await seed(RECORD, '{ this is not json')

    const build = await syncOutput({
      mode: 'build',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes() },
    })
    expect(codes(build.diagnostics)).toEqual(['LZ5007'])

    await seed(RECORD, '{ this is not json')
    const checked = await syncOutput({
      mode: 'check',
      root,
      outDir: OUT_DIR,
      files: [],
      record: { path: RECORD, bytes: recordBytes() },
    })
    expect(codes(checked.diagnostics)).toEqual(['LZ5003'])
  })
})
