import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { runInit } from './init'
import { CI_SNIPPET, INSTALL_NOTE, PACKAGE_SCRIPTS } from './templates'

const GENERATED = '// @generated by loclizr abi=1. Do not edit; run `loclizr build`.\nexport {}\n'

let root = ''

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), 'loclizr-cli-init-edge-'))
})

afterEach(async () => {
  await rm(root, { recursive: true, force: true })
})

async function write(relative: string, content: string): Promise<void> {
  const file = join(root, relative)
  await mkdir(join(file, '..'), { recursive: true })
  await writeFile(file, content, 'utf8')
}

function read(relative: string): Promise<string> {
  return readFile(join(root, relative), 'utf8')
}

const HARD_GATE = "\n  severity: { 'ambiguous-source': 'error' },"
const SOFT_GATE = "// severity: { 'ambiguous-source': 'error' },"

describe('the workspace a sibling tree is searched in', () => {
  it('is marked by a package.json workspaces field', async () => {
    await write('package.json', JSON.stringify({ private: true, workspaces: ['packages/*'] }))
    await write('packages/ui/src/loclizr/messages.js', GENERATED)

    await runInit({ cwd: join(root, 'packages/app') })

    expect(await read('packages/app/loclizr.config.ts')).toContain('augmentLocale: false,')
  })

  it('is marked by a .git file, the shape a worktree has', async () => {
    await write('.git', 'gitdir: /elsewhere/.git/worktrees/x\n')
    await write('packages/ui/src/loclizr/messages.js', GENERATED)

    await runInit({ cwd: join(root, 'packages/app') })

    expect(await read('packages/app/loclizr.config.ts')).toContain('augmentLocale: false,')
  })

  it('is not marked by a package.json that names no workspaces', async () => {
    await write('package.json', '{"name":"root"}')
    await write('packages/ui/src/loclizr/messages.js', GENERATED)

    await runInit({ cwd: join(root, 'packages/app') })

    expect(await read('packages/app/loclizr.config.ts')).not.toContain('augmentLocale')
  })

  it('is not marked by a package.json it cannot parse', async () => {
    await write('package.json', '{ "workspaces": [')
    await write('packages/ui/src/loclizr/messages.js', GENERATED)

    await runInit({ cwd: join(root, 'packages/app') })

    expect(await read('packages/app/loclizr.config.ts')).not.toContain('augmentLocale')
  })

  it('is not marked by a __proto__ key that JSON.parse keeps as data', async () => {
    await write('package.json', '{"__proto__":{"workspaces":["packages/*"]}}')
    await write('packages/ui/src/loclizr/messages.js', GENERATED)

    await runInit({ cwd: join(root, 'packages/app') })

    expect(await read('packages/app/loclizr.config.ts')).not.toContain('augmentLocale')
  })
})

describe('what counts as a generated tree', () => {
  it('ignores a header that is not at the first byte', async () => {
    await write('packages/ui/src/loclizr/messages.js', `\n${GENERATED}`)

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).not.toContain('augmentLocale')
  })

  it('ignores a header the file only quotes later on', async () => {
    await write('src/other/messages.js', `const marker = '${'// @generated by loclizr'}'\n`)

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).not.toContain('augmentLocale')
  })

  it('ignores a generated tree under dist', async () => {
    await write('packages/ui/dist/loclizr/messages.js', GENERATED)

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).not.toContain('augmentLocale')
  })

  it('finds a generated tree at a non default outDir in the same project', async () => {
    await write('app/i18n-generated/messages.js', GENERATED)

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain('augmentLocale: false,')
  })

  it('answers the same whatever the header line ending', async () => {
    await write('packages/ui/src/loclizr/messages.js', GENERATED.replaceAll('\n', '\r\n'))

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain('augmentLocale: false,')
  })
})

describe('greenfield or retrofit, from the source catalog', () => {
  it('reads a whitespace only catalog as empty', async () => {
    await write('locales/en.json', ' \n\t\r\n ')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(HARD_GATE)
  })

  it('reads an empty object with CRLF endings as empty', async () => {
    await write('locales/en.json', '{\r\n}\r\n')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(HARD_GATE)
  })

  it('reads an empty object with a lone CR as empty', async () => {
    await write('locales/en.json', '{}\r')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(HARD_GATE)
  })

  it('reads a catalog whose only key is __proto__ as populated', async () => {
    await write('locales/en.json', '{"__proto__":{"a":"b"}}')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(SOFT_GATE)
  })

  it('reads a catalog whose only key is constructor as populated', async () => {
    await write('locales/en.json', '{"constructor":"Konstruktor"}')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(SOFT_GATE)
  })

  it('reads an array root as populated rather than as empty', async () => {
    await write('locales/en.json', '[]')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(SOFT_GATE)
  })

  it('reads a top level null as populated rather than as empty', async () => {
    await write('locales/en.json', 'null')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(SOFT_GATE)
  })

  it('reads a catalog holding only emoji and RTL text as populated', async () => {
    await write('locales/en.json', '{"גשר":"‫שלום 👋‬"}')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(SOFT_GATE)
  })
})

describe('which existing config it refuses to shadow', () => {
  it('names a loclizr.config.mjs that stands alone', async () => {
    await write('loclizr.config.mjs', 'export default {}\n')

    const { output } = await runInit({ cwd: root })

    expect(output).toContain('loclizr.config.mjs already exists, left unchanged')
    await expect(read('loclizr.config.ts')).rejects.toThrow()
  })

  it('names a loclizr.config.mts that stands alone', async () => {
    await write('loclizr.config.mts', 'export default {}\n')

    const { output } = await runInit({ cwd: root })

    expect(output).toContain('loclizr.config.mts already exists, left unchanged')
  })

  it('names the .ts when several configs exist, the one discovery reads first', async () => {
    await write('loclizr.config.js', 'export default {}\n')
    await write('loclizr.config.ts', 'export default {}\n')

    const { output } = await runInit({ cwd: root })

    expect(output).toContain('loclizr.config.ts already exists, left unchanged')
    expect(output).not.toContain('loclizr.config.js')
  })

  it('ignores a config with a name discovery never reads', async () => {
    await write('loclizr.config.cjs', 'module.exports = {}\n')

    const { output } = await runInit({ cwd: root })

    expect(output).toContain('wrote loclizr.config.ts')
  })

  it('skips the shadow check when --config names the target explicitly', async () => {
    await write('loclizr.config.js', 'export default {}\n')

    const result = await runInit({ cwd: root, configPath: 'loclizr.config.ts' })

    expect(result.output).toContain('wrote loclizr.config.ts')
    expect(await read('loclizr.config.js')).toBe('export default {}\n')
  })

  it('writes the seed beside a config written through --config', async () => {
    const result = await runInit({ cwd: root, configPath: 'tools/loclizr.config.mts' })

    expect(result.output).toContain('wrote locales/en.json')
  })

  it('prints a --config given as an absolute path relative to --cwd', async () => {
    const result = await runInit({ cwd: root, configPath: join(root, 'cfg', 'loclizr.config.ts') })

    expect(result.output).toContain('wrote cfg/loclizr.config.ts')
    expect(result.output).not.toContain(root)
  })
})

describe('the source locale over unusual catalogs', () => {
  it('declares a regional locale when that is the only one on disk', async () => {
    await write('locales/en-US.json', '{"a":"b"}')

    const result = await runInit({ cwd: root })
    const config = await read('loclizr.config.ts')

    expect(config).toContain("sourceLocale: 'en-US',")
    expect(config).toContain('locales/en-US.meta.json')
    expect(result.output).toContain('locales/en-US.json already exists, left unchanged')
  })

  it('keeps en over en-US when both are on disk', async () => {
    await write('locales/en-US.json', '{}')
    await write('locales/en.json', '{}')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain("sourceLocale: 'en',")
  })

  it('declares an extension subtag locale verbatim', async () => {
    await write('locales/en-u-nu-latn.json', '{}')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain("sourceLocale: 'en-u-nu-latn',")
  })

  it('ignores catalogs in a sibling package it was not pointed at', async () => {
    await write('pnpm-workspace.yaml', "packages:\n  - 'packages/*'\n")
    await write('packages/ui/locales/de.json', '{"a":"b"}')

    const result = await runInit({ cwd: join(root, 'packages/app') })

    expect(await read('packages/app/loclizr.config.ts')).toContain("sourceLocale: 'en',")
    expect(result.output).toContain('wrote locales/en.json')
  })
})

describe('the shape of what it prints and writes', () => {
  it('prints the outcome, then install, scripts and CI, each once, in that order', async () => {
    const { output } = await runInit({ cwd: root })
    const at = [INSTALL_NOTE, PACKAGE_SCRIPTS, CI_SNIPPET].map((block) => output.indexOf(block))

    expect(at.every((index) => index > 0)).toBe(true)
    expect([...at].sort((a, b) => a - b)).toEqual(at)
    expect(output.split(CI_SNIPPET)).toHaveLength(2)
  })

  it('ends its output with exactly one newline', async () => {
    const { output } = await runInit({ cwd: root })

    expect(output.endsWith('\n')).toBe(true)
    expect(output.endsWith('\n\n')).toBe(false)
  })

  it('ends a failed run with exactly one newline too', async () => {
    await write('locales', '')

    const { output, ok } = await runInit({ cwd: root })

    expect(ok).toBe(false)
    expect(output.endsWith('\n')).toBe(true)
    expect(output.endsWith('\n\n')).toBe(false)
  })

  it('names no absolute path, so two machines print the same text', async () => {
    await write('public/locales/en/common.json', '{}')

    const { output } = await runInit({ cwd: root })

    expect(output).not.toContain(root)
  })

  it('writes a config with LF endings, no trailing whitespace and one final newline', async () => {
    await runInit({ cwd: root })
    const config = await read('loclizr.config.ts')

    expect(config).not.toContain('\r')
    expect(config.endsWith('\n')).toBe(true)
    expect(config.endsWith('\n\n')).toBe(false)
    for (const line of config.split('\n')) expect(line).toBe(line.trimEnd())
  })

  it('writes a config with no long dash in it', async () => {
    await write('locales/en.json', '{"a":"b"}')
    await write('packages/ui/src/loclizr/messages.js', GENERATED)

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).not.toMatch(/[\u2013\u2014]/)
  })

  it('writes a config whose non ASCII catalog path survives as UTF-8', async () => {
    await write('приложение/locales/de.json', '{}')

    await runInit({ cwd: root })

    expect(await read('loclizr.config.ts')).toContain(
      "catalogs: 'приложение/locales/{locale}.json',",
    )
  })
})
