export const CONFIG_FILENAMES: readonly string[] = [
  'loclizr.config.ts',
  'loclizr.config.mts',
  'loclizr.config.js',
  'loclizr.config.mjs',
]

export const CONFIG_FILENAME: string = 'loclizr.config.ts'
export const CATALOG_DIR: string = 'locales'
export const DEFAULT_CATALOGS: string = `${CATALOG_DIR}/{locale}.json`
export const DEFAULT_SOURCE_LOCALE: string = 'en'
export const DEFAULT_META: string = `${CATALOG_DIR}/{sourceLocale}.meta.json`
export const SEED_OUT_DIR: string = 'src/loclizr'
export const GENERATED_MARKER: string = '// @generated by loclizr'

export function catalogPath(locale: string): string {
  return `${CATALOG_DIR}/${locale}.json`
}

export interface ConfigTemplateOptions {
  readonly locales: readonly string[] | null
  readonly catalogs: string
  readonly meta: string | null
  readonly greenfield: boolean
  readonly augmentLocale: boolean
  readonly sourceLocale: string
}

// ICU, so the file classifies as ICU under `catalogFormat: 'auto'` and keeps
// doing so once an imported i18next file lands beside it. A plural written out
// rather than an `_one` / `_other` pair is what decides that.
export const SEED_CATALOG: string = `{
  "nav": {
    "home": "Home",
    "cart": "Cart"
  },
  "cart": {
    "greeting": "Hi {name}, your cart is ready",
    "items": "{count, plural, =0 {Your cart is empty} one {# item in your cart} other {# items in your cart}}"
  }
}
`

// The catalogs pattern carries whatever directory names discovery walked
// through, so an apostrophe or a control character in one has to be escaped
// for the config to parse.
function singleQuoted(value: string): string {
  return `'${JSON.stringify(value).slice(1, -1).replaceAll("'", "\\'")}'`
}

export function configTemplate(options: ConfigTemplateOptions): string {
  const lines: string[] = [
    "import { defineConfig } from 'loclizr'",
    '',
    'export default defineConfig({',
  ]
  if (options.locales !== null) {
    lines.push(`  locales: [${options.locales.map(singleQuoted).join(', ')}],`)
  }
  lines.push(
    `  sourceLocale: '${options.sourceLocale}',`,
    `  catalogs: ${singleQuoted(options.catalogs)},`,
  )
  if (options.meta !== null) lines.push(`  meta: ${singleQuoted(options.meta)},`)
  lines.push(`  outDir: '${SEED_OUT_DIR}',`)
  const metaPath = (options.meta ?? DEFAULT_META).replace('{sourceLocale}', options.sourceLocale)
  if (!options.augmentLocale) {
    lines.push(
      '  // Another generated tree already exists here. Two of them declaring the',
      '  // locale registry in one TypeScript program is TS2717, reported inside',
      '  // generated files, and the app stops compiling.',
      '  augmentLocale: false,',
    )
  }
  if (options.greenfield) {
    lines.push("  severity: { 'ambiguous-source': 'error' },")
  } else {
    lines.push(
      `  // Turn this on once ${metaPath} describes your keys. It`,
      '  // reports keys that share source text where at least one of them has no',
      '  // description, so on a catalog imported without descriptions it fires on',
      '  // every shared string at once.',
      "  // severity: { 'ambiguous-source': 'error' },",
    )
  }
  lines.push('})', '')
  return lines.join('\n')
}

// The config this writes opens with `import { defineConfig } from 'loclizr'`,
// so `npx loclizr init` followed by `npx loclizr build` dies on a missing
// module unless the package is a dependency of the project itself. A regular
// dependency, not a dev one: the generated functions import the locale store
// from `loclizr` at run time, and a Node server has to find it after install.
// The note names the config init wrote or kept, which `--config` or an
// existing `loclizr.config.js` makes something other than the default.
export function installNote(configPath: string): string {
  return `Install loclizr, which ${configPath} and the generated code import:

  npm i loclizr`
}

// No `prepare` hook: it runs on `npm ci`, so a CI install would rewrite the
// context record before `loclizr check` compares it and the gate would pass
// on a stale record. The three `pre*` hooks cover every command a developer
// runs; a fresh clone has no generated tree until the first of them.
export const PACKAGE_SCRIPTS: string = `Add these scripts to package.json:

  "predev": "loclizr build --no-fail",
  "prebuild": "loclizr build",
  "pretypecheck": "loclizr build"`

export const CI_SNIPPET: string = `Add this step to CI, before any step that runs loclizr build:

  # loclizr check compares the committed context record against this tree.
  # loclizr build would rewrite that record in the CI workspace and pass.
  - run: npx loclizr check`
