export const CONFIG_FILENAMES: readonly string[] = [
  'loclizr.config.ts',
  'loclizr.config.mts',
  'loclizr.config.js',
  'loclizr.config.mjs',
]

export const CONFIG_FILENAME: string = 'loclizr.config.ts'
export const CATALOG_DIR: string = 'locales'
export const DEFAULT_CATALOGS: string = `${CATALOG_DIR}/{locale}.json`
export const DEFAULT_SOURCE_LOCALE: string = 'en'
export const SEED_OUT_DIR: string = 'src/loclizr'
export const GENERATED_MARKER: string = '// @generated by loclizr'

export function catalogPath(locale: string): string {
  return `${CATALOG_DIR}/${locale}.json`
}

export interface ConfigTemplateOptions {
  readonly catalogs: string
  readonly greenfield: boolean
  readonly augmentLocale: boolean
  readonly sourceLocale: string
}

// ICU, so the file classifies as ICU under `catalogFormat: 'auto'` and keeps
// doing so once an imported i18next file lands beside it. A plural written out
// rather than an `_one` / `_other` pair is what decides that.
export const SEED_CATALOG: string = `{
  "nav": {
    "home": "Home",
    "cart": "Cart"
  },
  "cart": {
    "greeting": "Hi {name}, your cart is ready",
    "items": "{count, plural, =0 {Your cart is empty} one {# item in your cart} other {# items in your cart}}"
  }
}
`

export function configTemplate(options: ConfigTemplateOptions): string {
  const lines: string[] = [
    "import { defineConfig } from 'loclizr'",
    '',
    'export default defineConfig({',
    `  sourceLocale: '${options.sourceLocale}',`,
    `  catalogs: '${options.catalogs}',`,
    `  outDir: '${SEED_OUT_DIR}',`,
  ]
  if (!options.augmentLocale) {
    lines.push(
      '  // Another generated tree already exists here. Two of them declaring the',
      '  // locale registry in one TypeScript program is TS2717, reported inside',
      '  // generated files, and the app stops compiling.',
      '  augmentLocale: false,',
    )
  }
  if (options.greenfield) {
    lines.push("  severity: { 'ambiguous-source': 'error' },")
  } else {
    lines.push(
      `  // Turn this on once ${CATALOG_DIR}/${options.sourceLocale}.meta.json describes your keys. It`,
      '  // reports keys that share source text where at least one of them has no',
      '  // description, so on a catalog imported without descriptions it fires on',
      '  // every shared string at once.',
      "  // severity: { 'ambiguous-source': 'error' },",
    )
  }
  lines.push('})', '')
  return lines.join('\n')
}

// The config this writes opens with `import { defineConfig } from 'loclizr'`,
// so `npx loclizr init` followed by `npx loclizr build` dies on a missing
// module unless the package is a dependency of the project itself.
export const INSTALL_NOTE: string = `Install loclizr, which loclizr.config.ts imports:

  npm i -D loclizr`

export const PACKAGE_SCRIPTS: string = `Add these scripts to package.json:

  "prepare": "loclizr build --no-fail",
  "predev": "loclizr build --no-fail",
  "prebuild": "loclizr build",
  "pretypecheck": "loclizr build"`

export const CI_SNIPPET: string = `Add this step to CI:

  # loclizr check compares the committed context record against this tree.
  # loclizr build would rewrite that record in the CI workspace and pass.
  - run: npx loclizr check`
