// Every value here must lower, so the round trip covers it. Values that fail to
// parse belong in the diagnostic tests instead.
export const CORPUS: readonly string[] = [
  '',
  'Home',
  "Don't stop",
  'Set {color} in CSS',
  'Order #42 shipped',
  'A < B and C > D',
  'a } b',
  "'{'literal'}'",
  'Hi {name}, your cart is ready',
  'Total: {amount, number, ::currency/USD}',
  'Too many requests. Try again in {seconds, number} seconds.',
  '{ratio, number, percent} done',
  '{n, number, integer} files',
  'Updated {at, date, medium}',
  'Doors at {at, time, short}',
  '{at, date} and {at, time}',
  '{d, date, ::yyyyMMdd}',
  '{d, date, ::yyyy MMM dd}',
  '{d, date, ::qqqq}',
  '{count, plural, =0 {Your cart is empty} one {# item in your cart} other {# items in your cart}}',
  '{count, plural, offset:2 one {# left} other {# left}}',
  '{place, selectordinal, one {#st} two {#nd} few {#rd} other {#th}}',
  '{c, plural, other {{g, select, male {he} other {they}} has # left}}',
  '{a, plural, offset:1 other {# and {b, select, x {#} other {#}}}}',
  '{c, plural, other {{y}} one {{x}}}',
  '{c, plural, one {{x}} =3 {{z}} other {{y}}}',
  '{c, plural, other {}}',
  '{c, plural, =-1 {x} other {y}}',
  '{c, plural, =0 {a} =007 {b} other {c}}',
  '{a, plural, other {{b, plural, other {#}}}}',
  '{c, plural, other {{g, select, other {<b>#</b>}}}}',
  '{state, select, shipped {On its way} delivered {Delivered} other {Processing}}',
  '{rank, select, 1 {gold} 0 {none} other {other}}',
  '{s, select, other {anything}}',
  'Read our <link>terms</link> before you continue.',
  'Nested <b>bold <i>and italic</i></b> end',
  '{c, plural, one {<b># file</b>} other {<b># files</b>}}',
  '{files, plural, one {# file} other {# files}} in {folders, plural, one {# folder} other {# folders}}',
  '{d, date, medium} at {d, time, short}',
  'Hi {name}, you have {name} messages',
  'Use {a} then {b} then {a}',
  "It's {n, plural, one {# item} other {# items}} and it's fine",
]
