import type { Arg, IntlOptions, Message } from '../types'
import { compareCodepoint, hash16, stableStringify } from '../util'

export const HEADER: string = '// @generated by loclizr abi=1. Do not edit; run `loclizr build`.'

// A checkJs project would otherwise typecheck generated code, while the
// sibling .d.ts already carries the types and stays checked.
export const NOCHECK: string = '// @ts-nocheck'

export const PLURAL_KEYWORDS: readonly string[] = ['zero', 'one', 'two', 'few', 'many', 'other']

export const MAX_LINE: number = 120

const IDENTIFIER = /^[\p{ID_Start}$_][\p{ID_Continue}$]*$/u

const UNPAIRED_SURROGATE = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/gu

export function pad(indent: number): string {
  return ' '.repeat(indent)
}

export function isIdentifier(name: string): boolean {
  return IDENTIFIER.test(name)
}

// LZ2007's predicate. `__proto__` lexes as an identifier, but the rule rejects
// it, and section 7.2 reaches every name the rule rejects by subscript.
export function isArgName(name: string): boolean {
  return isIdentifier(name) && name !== '__proto__'
}

export function property(name: string): string {
  return isIdentifier(name) ? name : quoted(name)
}

// JSON writes NaN and both infinities as null, which would give three option
// sets one name and render one with another's options. An option value is
// never an array, so wrapping the spelling in one cannot meet a real value,
// while a finite option set still hashes exactly its canonical JSON.
export function formatName(options: IntlOptions): string {
  const canonical = Object.fromEntries(
    Object.entries(options).map(([key, value]) => [
      key,
      typeof value === 'number' && !Number.isFinite(value) ? [String(value)] : value,
    ]),
  )
  return `$f${hash16(stableStringify(canonical))}`
}

export function byCodepoint(values: readonly string[]): readonly string[] {
  return [...values].sort(compareCodepoint)
}

// UTF-8 cannot carry half a surrogate pair, so writing one lands U+FFFD on disk
// and the bytes read back never equal the bytes emit produced: every build
// rewrites the file and `check` calls the tree `build` just wrote stale.
function withoutUnpairedSurrogates(value: string): string {
  return value.replace(
    UNPAIRED_SURROGATE,
    (half) => `\\u${half.charCodeAt(0).toString(16).padStart(4, '0')}`,
  )
}

// Every `$` is escaped: text nodes are concatenated into one template literal,
// so a node ending in `$` beside a node starting with `{` would otherwise join
// into a live interpolation of catalog text.
export function templateText(value: string): string {
  return withoutUnpairedSurrogates(
    value
      .replaceAll('\\', '\\\\')
      .replaceAll('`', '\\`')
      .replaceAll('$', '\\$')
      .replaceAll('\r', '\\r')
      .replaceAll('\n', '\\n')
      .replaceAll(' ', '\\u2028')
      .replaceAll(' ', '\\u2029'),
  )
}

export function quoted(value: string): string {
  const escaped = withoutUnpairedSurrogates(
    value
      .replaceAll('\\', '\\\\')
      .replaceAll("'", "\\'")
      .replaceAll('\r', '\\r')
      .replaceAll('\n', '\\n')
      .replaceAll(' ', '\\u2028')
      .replaceAll(' ', '\\u2029'),
  )
  return `'${escaped}'`
}

// A source string holding `*/` would close the comment early and print a .d.ts
// no rule catches, because LZ4005 compares two equally broken passes.
export function docComment(locale: string, source: string): string {
  const text = withoutUnpairedSurrogates(source.replaceAll('*/', '*\\/').replace(/\r\n|\r|\n/gu, ' '))
  return `/** ${locale}: "${text}" */`
}

// A handler argument names T in the parameter list and a markup message names
// it in the return, so either alone still has to bind it on the declaration.
export function bindsHandlerType(message: Message): boolean {
  return message.kind === 'markup' || message.args.some((entry) => entry.type.kind === 'markup')
}

export function handlerNames(args: readonly Arg[]): ReadonlySet<string> {
  return new Set(args.filter((entry) => entry.type.kind === 'markup').map((entry) => entry.name))
}

export function objectLiteral(options: IntlOptions): string {
  const keys = byCodepoint(Object.keys(options))
  if (keys.length === 0) return '{}'
  const fields = keys.map((key) => `${property(key)}: ${literal(options[key])}`)
  return `{ ${fields.join(', ')} }`
}

export function textOf(lines: readonly string[]): string {
  return `${lines.join('\n')}\n`
}

function literal(value: string | number | boolean | undefined): string {
  return typeof value === 'string' ? quoted(value) : String(value)
}
