import type { IntlOptions } from '../types'
import { compareCodepoint, hash16, stableStringify } from '../util'

export const HEADER: string = '// @generated by loclizr abi=1. Do not edit; run `loclizr build`.'

export const PLURAL_KEYWORDS: readonly string[] = ['zero', 'one', 'two', 'few', 'many', 'other']

export const MAX_LINE: number = 120

export function pad(indent: number): string {
  return ' '.repeat(indent)
}

export function formatName(options: IntlOptions): string {
  return `$f${hash16(stableStringify(options))}`
}

export function byCodepoint(values: readonly string[]): readonly string[] {
  return [...values].sort(compareCodepoint)
}

export function templateText(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll(' ', '\\u2028')
    .replaceAll(' ', '\\u2029')
}

export function quoted(value: string): string {
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll(' ', '\\u2028')
    .replaceAll(' ', '\\u2029')
  return `'${escaped}'`
}

// A source string holding `*/` would close the comment early and print a .d.ts
// no rule catches, because LZ4005 compares two equally broken passes.
export function docComment(locale: string, source: string): string {
  const text = source.replaceAll('*/', '*\\/').replace(/\r\n|\r|\n/gu, ' ')
  return `/** ${locale}: "${text}" */`
}

export function objectLiteral(options: IntlOptions): string {
  const keys = byCodepoint(Object.keys(options))
  if (keys.length === 0) return '{}'
  const fields = keys.map((key) => `${key}: ${literal(options[key])}`)
  return `{ ${fields.join(', ')} }`
}

export function textOf(lines: readonly string[]): string {
  return `${lines.join('\n')}\n`
}

function literal(value: string | number | boolean | undefined): string {
  return typeof value === 'string' ? quoted(value) : String(value)
}
