// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
export const $f44136fa355b3678a = /*#__PURE__*/ Object.freeze({})
export const $f56d532f63ea89042 = /*#__PURE__*/ Object.freeze({ currency: 'USD', style: 'currency' })
export const $f67d978756bf2d048 = /*#__PURE__*/ Object.freeze({ dateStyle: 'medium' })
