// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { IntlOptions } from 'loclizr'
export declare const $f44136fa355b3678a: IntlOptions
export declare const $f56d532f63ea89042: IntlOptions
export declare const $f67d978756bf2d048: IntlOptions
