// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import { $configure1 } from 'loclizr'

export const locales = /*#__PURE__*/ Object.freeze(['de', 'de-AT', 'en'])
export const sourceLocale = 'en'
export const $l = $configure1({ locales, sourceLocale, cookie: 'locale' })
