// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import { $dateTime1, $number1, $plural1 } from 'loclizr'
import { $f44136fa355b3678a, $f56d532f63ea89042, $f67d978756bf2d048 } from './_formats.js'
import { $l } from './_locale.js'

export function cart_counts(args, opts) {
  const l = $l(opts)
  const n0 = args.files
  const n1 = args.folders
  switch (l) {
    case 'de':
    case 'de-AT':
      return `${
        $plural1('de', n0, false) === 'one'
          ? `${$number1(l, n0, $f44136fa355b3678a)} Datei`
          : `${$number1(l, n0, $f44136fa355b3678a)} Dateien`
      } in ${
        $plural1('de', n1, false) === 'one'
          ? `${$number1(l, n1, $f44136fa355b3678a)} Ordner`
          : `${$number1(l, n1, $f44136fa355b3678a)} Ordnern`
      }`
    default:
      return `${
        $plural1('en', n0, false) === 'one'
          ? `${$number1(l, n0, $f44136fa355b3678a)} file`
          : `${$number1(l, n0, $f44136fa355b3678a)} files`
      } in ${
        $plural1('en', n1, false) === 'one'
          ? `${$number1(l, n1, $f44136fa355b3678a)} folder`
          : `${$number1(l, n1, $f44136fa355b3678a)} folders`
      }`
  }
}

export function cart_greeting(args, opts) {
  switch ($l(opts)) {
    case 'de':
      return `Hallo ${args.name}, dein Warenkorb ist fertig`
    case 'de-AT':
      return `Servus ${args.name}, dein Warenkorb ist fertig`
    default:
      return `Hi ${args.name}, your cart is ready`
  }
}

export function cart_items(args, opts) {
  const l = $l(opts)
  const n0 = args.count
  switch (l) {
    case 'de':
    case 'de-AT':
      if (n0 === 0) return `Dein Warenkorb ist leer`
      return `${args.count} Artikel in deinem Warenkorb`
    default:
      if (n0 === 0) return `Your cart is empty`
      switch ($plural1('en', n0, false)) {
        case 'one':
          return `${$number1(l, n0, $f44136fa355b3678a)} item in your cart`
        default:
          return `${$number1(l, n0, $f44136fa355b3678a)} items in your cart`
      }
  }
}

export function cart_nested(args, opts) {
  const l = $l(opts)
  const n0 = args.users
  const n1 = args.files
  switch (l) {
    default:
      if (n0 === 0) return `nobody`
      switch ($plural1('en', n0 - 2, false)) {
        case 'one':
          switch ($plural1('en', n1, false)) {
            case 'one':
              return `one user, one file`
            default:
              return `${$number1(l, n1, $f44136fa355b3678a)} files for one user`
          }
        default:
          return `${$number1(l, n0 - 2, $f44136fa355b3678a)} users, ${
            $plural1('en', n1, false) === 'one'
              ? `one file`
              : `${$number1(l, n1, $f44136fa355b3678a)} files`
          }`
      }
  }
}

export function cart_total(args, opts) {
  const l = $l(opts)
  switch (l) {
    case 'de':
    case 'de-AT':
      return `Summe: ${$number1(l, args.amount, $f56d532f63ea89042)}`
    default:
      return `Total: ${$number1(l, args.amount, $f56d532f63ea89042)}`
  }
}

export function cart_updated(args, opts) {
  const l = $l(opts)
  switch (l) {
    case 'de':
    case 'de-AT':
      return `Aktualisiert ${$dateTime1(l, args.at, $f67d978756bf2d048)}`
    default:
      return `Updated ${$dateTime1(l, args.at, $f67d978756bf2d048)}`
  }
}
