// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { MessageOptions } from 'loclizr'
/** en: "{files, plural, one {# file} other {# files}} in {folders, plural, one {# folder} other {# folders}}" */
export declare function cart_counts(args: { files: number; folders: number }, opts?: MessageOptions): string
/** en: "Hi {name}, your cart is ready" */
export declare function cart_greeting(args: { name: string | number }, opts?: MessageOptions): string
/** en: "{count, plural, =0 {Your cart is empty} one {# item in your cart} other {# items in your cart}}" */
export declare function cart_items(args: { count: number }, opts?: MessageOptions): string
/** en: "{users, plural, offset:2 =0 {nobody} one {{files, plural, one {one user, one file} other {# files for one user}}} other {# users, {files, plural, one {one file} other {# files}}}}" */
export declare function cart_nested(args: { users: number; files: number }, opts?: MessageOptions): string
/** en: "Total: {amount, number, ::currency/USD}" */
export declare function cart_total(args: { amount: number }, opts?: MessageOptions): string
/** en: "Updated {at, date, medium}" */
export declare function cart_updated(args: { at: Date | number }, opts?: MessageOptions): string
