// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import { $l } from './_locale.js'

export function dev_snippet(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Passt auf /x*/ in einem Kommentar`
    default:
      return `Matches /x*/ in a comment`
  }
}
