// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { EmptyArgs, MessageOptions } from 'loclizr'
/** en: "Matches /x*\/ in a comment" */
export declare function dev_snippet(args?: EmptyArgs, opts?: MessageOptions): string
