// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { EmptyArgs, MessageOptions } from 'loclizr'
/** en: "You do not have access" */
export declare function errors_forbidden(args?: EmptyArgs, opts?: MessageOptions): string
/** en: "We could not find that page" */
export declare function errors_not_found(args?: EmptyArgs, opts?: MessageOptions): string
/** en: "Too many requests. Try again in {seconds, number} seconds." */
export declare function errors_rate_limited(args: { seconds: number }, opts?: MessageOptions): string
