// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
import { $number1 } from 'loclizr'
import { $f44136fa355b3678a } from './_formats.js'
import { $l } from './_locale.js'

export function errors_forbidden(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Du hast keinen Zugriff`
    default:
      return `You do not have access`
  }
}

export function errors_not_found(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Wir konnten die Seite nicht finden`
    default:
      return `We could not find that page`
  }
}

export function errors_rate_limited(args, opts) {
  const l = $l(opts)
  switch (l) {
    case 'de':
    case 'de-AT':
      return `Zu viele Anfragen. Versuche es in ${$number1(l, args.seconds, $f44136fa355b3678a)} Sekunden erneut.`
    default:
      return `Too many requests. Try again in ${$number1(l, args.seconds, $f44136fa355b3678a)} seconds.`
  }
}
