// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { EmptyArgs, MessageOptions } from 'loclizr'
/** en: "Cart" */
export declare function nav_cart(args?: EmptyArgs, opts?: MessageOptions): string
/** en: "Home" */
export declare function nav_home(args?: EmptyArgs, opts?: MessageOptions): string
