// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
import { $l } from './_locale.js'

export function nav_cart(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Warenkorb`
    default:
      return `Cart`
  }
}

export function nav_home(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Startseite`
    default:
      return `Home`
  }
}
