// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
import { $l } from './_locale.js'

export function order_status(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      switch (args.state) {
        case 'delivered':
          return `Zugestellt`
        case 'shipped':
          return `Unterwegs`
        default:
          return `In Bearbeitung`
      }
    default:
      switch (args.state) {
        case 'delivered':
          return `Delivered`
        case 'shipped':
          return `On its way`
        default:
          return `Processing`
      }
  }
}
