// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { MessageOptions } from 'loclizr'
/** en: "{state, select, shipped {On its way} delivered {Delivered} other {Processing}}" */
export declare function order_status(args: { state: 'delivered' | 'shipped' }, opts?: MessageOptions): string
