// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
// @ts-nocheck
import { $number1, $plural1 } from 'loclizr'
import { $f44136fa355b3678a } from './_formats.js'
import { $l } from './_locale.js'

export function terms_accept(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return ['Lies unsere ', args.link(['AGB']), ', bevor du fortfährst.']
    default:
      return ['Read our ', args.link(['terms']), ' before you continue.']
  }
}

export function terms_bare(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Klick hier jetzt`
    default:
      return `Click  now`
  }
}

export function terms_dropped(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return [`Bitte lies das jetzt.`]
    default:
      return ['Please ', args.notice(['read this']), ' now.']
  }
}

export function terms_notice(args, opts) {
  const l = $l(opts)
  const n0 = args.count
  switch (l) {
    case 'de':
    case 'de-AT':
      return [
        'Du hast ',
        ...($plural1('de', n0, false) === 'one'
          ? [args.b(['eine Datei'])]
          : [args.b([`${$number1(l, n0, $f44136fa355b3678a)} Dateien`])]),
        ' zu lesen',
      ]
    default:
      return [
        'You have ',
        ...($plural1('en', n0, false) === 'one'
          ? [args.b(['one file'])]
          : [args.b([`${$number1(l, n0, $f44136fa355b3678a)} files`])]),
        ' to read',
      ]
  }
}

export function terms_title(args, opts) {
  switch ($l(opts)) {
    case 'de':
    case 'de-AT':
      return `Nutzungsbedingungen`
    default:
      return `Terms of service`
  }
}
