// @generated by loclizr abi=1. Do not edit; run `loclizr build`.
import type { EmptyArgs, MessageOptions } from 'loclizr'
/** en: "Read our <link>terms</link> before you continue." */
export declare function terms_accept<T>(
  args: { link: (chunks: readonly (string | T)[]) => T },
  opts?: MessageOptions,
): readonly (string | T)[]
/** en: "Click {link} now" */
export declare function terms_bare<T>(
  args: { link: (chunks: readonly (string | T)[]) => T },
  opts?: MessageOptions,
): string
/** en: "Please <notice>read this</notice> now." */
export declare function terms_dropped<T>(
  args: { notice: (chunks: readonly (string | T)[]) => T },
  opts?: MessageOptions,
): readonly (string | T)[]
/** en: "You have {count, plural, one {<b>one file</b>} other {<b># files</b>}} to read" */
export declare function terms_notice<T>(
  args: { count: number; b: (chunks: readonly (string | T)[]) => T },
  opts?: MessageOptions,
): readonly (string | T)[]
/** en: "Terms of service" */
export declare function terms_title(args?: EmptyArgs, opts?: MessageOptions): string
